server:
  port: 8080

#spring:
#  datasource:
#    driverClassName: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://192.168.238.150:33006/my_test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8
#    username: root
#    password: 123456

spring:
  datasource:
    dynamic:
      primary: master # 设置默认的数据源或者数据源组,默认值即为master
      strict: false # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://192.168.238.150:33006/my_test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8
          username: root
          password: 123456
        slave_1:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://192.168.238.151:33006/test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8
          username: root
          password: 123456

mybatis-plus:
  mapper-locations: classpath*:com/mybatisplus/demo/mapper/xml/**/*.xml
  # 类型处理器所在的包
  type-handlers-package: com.mybatisplus.demo.mybatisplus.typehandler
  # 实体包扫描，多个package用逗号或者分号分隔，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)
  type-aliases-package: com.mybatisplus.demo.model.domain
  # 通用枚举包
  type-enums-package: com.mybatisplus.demo.enums
  global-config:
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 1 # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
    # 打印SQL语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl